/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiTestRouteImport } from './routes/ui-test'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimerRouteRouteImport } from './routes/_timer/route'
import { Route as TrainerIndexRouteImport } from './routes/trainer/index'
import { Route as TimerIndexRouteImport } from './routes/_timer/index'
import { Route as TrainerStatsRouteImport } from './routes/trainer/stats'
import { Route as TrainerSolvesRouteImport } from './routes/trainer/solves'
import { Route as PuzzlesNewRouteImport } from './routes/puzzles/new'
import { Route as PuzzlesCustomRouteImport } from './routes/puzzles/custom'
import { Route as TimerStatisticsRouteImport } from './routes/_timer/statistics'
import { Route as TimerSolvesRouteImport } from './routes/_timer/solves'
import { Route as TimerConfigurationRouteImport } from './routes/_timer/configuration'

const UiTestRoute = UiTestRouteImport.update({
  id: '/ui-test',
  path: '/ui-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRouteRoute = TimerRouteRouteImport.update({
  id: '/_timer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const TimerIndexRoute = TimerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimerRouteRoute,
} as any)
const TrainerStatsRoute = TrainerStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerSolvesRoute = TrainerSolvesRouteImport.update({
  id: '/solves',
  path: '/solves',
  getParentRoute: () => TrainerRoute,
} as any)
const PuzzlesNewRoute = PuzzlesNewRouteImport.update({
  id: '/puzzles/new',
  path: '/puzzles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesCustomRoute = PuzzlesCustomRouteImport.update({
  id: '/puzzles/custom',
  path: '/puzzles/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerStatisticsRoute = TimerStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => TimerRouteRoute,
} as any)
const TimerSolvesRoute = TimerSolvesRouteImport.update({
  id: '/solves',
  path: '/solves',
  getParentRoute: () => TimerRouteRoute,
} as any)
const TimerConfigurationRoute = TimerConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => TimerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TimerIndexRoute
  '/settings': typeof SettingsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/ui-test': typeof UiTestRoute
  '/configuration': typeof TimerConfigurationRoute
  '/solves': typeof TimerSolvesRoute
  '/statistics': typeof TimerStatisticsRoute
  '/puzzles/custom': typeof PuzzlesCustomRoute
  '/puzzles/new': typeof PuzzlesNewRoute
  '/trainer/solves': typeof TrainerSolvesRoute
  '/trainer/stats': typeof TrainerStatsRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/ui-test': typeof UiTestRoute
  '/configuration': typeof TimerConfigurationRoute
  '/solves': typeof TimerSolvesRoute
  '/statistics': typeof TimerStatisticsRoute
  '/puzzles/custom': typeof PuzzlesCustomRoute
  '/puzzles/new': typeof PuzzlesNewRoute
  '/trainer/solves': typeof TrainerSolvesRoute
  '/trainer/stats': typeof TrainerStatsRoute
  '/': typeof TimerIndexRoute
  '/trainer': typeof TrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_timer': typeof TimerRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/ui-test': typeof UiTestRoute
  '/_timer/configuration': typeof TimerConfigurationRoute
  '/_timer/solves': typeof TimerSolvesRoute
  '/_timer/statistics': typeof TimerStatisticsRoute
  '/puzzles/custom': typeof PuzzlesCustomRoute
  '/puzzles/new': typeof PuzzlesNewRoute
  '/trainer/solves': typeof TrainerSolvesRoute
  '/trainer/stats': typeof TrainerStatsRoute
  '/_timer/': typeof TimerIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/trainer'
    | '/ui-test'
    | '/configuration'
    | '/solves'
    | '/statistics'
    | '/puzzles/custom'
    | '/puzzles/new'
    | '/trainer/solves'
    | '/trainer/stats'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/ui-test'
    | '/configuration'
    | '/solves'
    | '/statistics'
    | '/puzzles/custom'
    | '/puzzles/new'
    | '/trainer/solves'
    | '/trainer/stats'
    | '/'
    | '/trainer'
  id:
    | '__root__'
    | '/_timer'
    | '/settings'
    | '/trainer'
    | '/ui-test'
    | '/_timer/configuration'
    | '/_timer/solves'
    | '/_timer/statistics'
    | '/puzzles/custom'
    | '/puzzles/new'
    | '/trainer/solves'
    | '/trainer/stats'
    | '/_timer/'
    | '/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TimerRouteRoute: typeof TimerRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TrainerRoute: typeof TrainerRouteWithChildren
  UiTestRoute: typeof UiTestRoute
  PuzzlesCustomRoute: typeof PuzzlesCustomRoute
  PuzzlesNewRoute: typeof PuzzlesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-test': {
      id: '/ui-test'
      path: '/ui-test'
      fullPath: '/ui-test'
      preLoaderRoute: typeof UiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timer': {
      id: '/_timer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TimerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/_timer/': {
      id: '/_timer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TimerIndexRouteImport
      parentRoute: typeof TimerRouteRoute
    }
    '/trainer/stats': {
      id: '/trainer/stats'
      path: '/stats'
      fullPath: '/trainer/stats'
      preLoaderRoute: typeof TrainerStatsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/solves': {
      id: '/trainer/solves'
      path: '/solves'
      fullPath: '/trainer/solves'
      preLoaderRoute: typeof TrainerSolvesRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/puzzles/new': {
      id: '/puzzles/new'
      path: '/puzzles/new'
      fullPath: '/puzzles/new'
      preLoaderRoute: typeof PuzzlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/custom': {
      id: '/puzzles/custom'
      path: '/puzzles/custom'
      fullPath: '/puzzles/custom'
      preLoaderRoute: typeof PuzzlesCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timer/statistics': {
      id: '/_timer/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof TimerStatisticsRouteImport
      parentRoute: typeof TimerRouteRoute
    }
    '/_timer/solves': {
      id: '/_timer/solves'
      path: '/solves'
      fullPath: '/solves'
      preLoaderRoute: typeof TimerSolvesRouteImport
      parentRoute: typeof TimerRouteRoute
    }
    '/_timer/configuration': {
      id: '/_timer/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof TimerConfigurationRouteImport
      parentRoute: typeof TimerRouteRoute
    }
  }
}

interface TimerRouteRouteChildren {
  TimerConfigurationRoute: typeof TimerConfigurationRoute
  TimerSolvesRoute: typeof TimerSolvesRoute
  TimerStatisticsRoute: typeof TimerStatisticsRoute
  TimerIndexRoute: typeof TimerIndexRoute
}

const TimerRouteRouteChildren: TimerRouteRouteChildren = {
  TimerConfigurationRoute: TimerConfigurationRoute,
  TimerSolvesRoute: TimerSolvesRoute,
  TimerStatisticsRoute: TimerStatisticsRoute,
  TimerIndexRoute: TimerIndexRoute,
}

const TimerRouteRouteWithChildren = TimerRouteRoute._addFileChildren(
  TimerRouteRouteChildren,
)

interface TrainerRouteChildren {
  TrainerSolvesRoute: typeof TrainerSolvesRoute
  TrainerStatsRoute: typeof TrainerStatsRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerSolvesRoute: TrainerSolvesRoute,
  TrainerStatsRoute: TrainerStatsRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TimerRouteRoute: TimerRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TrainerRoute: TrainerRouteWithChildren,
  UiTestRoute: UiTestRoute,
  PuzzlesCustomRoute: PuzzlesCustomRoute,
  PuzzlesNewRoute: PuzzlesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
